In [61]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
import os
import csv
import struct
import numpy as np
from scipy.interpolate import interp1d
from typing import List, Tuple
from numpy.core import ndarray
from dataclasses import dataclass
from sklearn.model_selection import LeaveOneOut
import math
from sklearn.utils import shuffle
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

In [2]:
def class_name_to_numeric(cn: str) -> int:
    if cn == "SARS-CoV":
        return 0
    elif cn == "SARS-CoV-2":
        return 1
    elif cn == "MERS-CoV":
        return 2
    elif cn == "HCoV-229E":
        return 3
    else:
        return 4

def class_name_to_numeric_p_n(cn: str) -> int:
    if cn == "Positive":
        return 0
    elif cn == "Negative":
        return 1
    else:
        return 4

def numeric_to_class_name(cn: int) -> str:
    if cn == 0:
        return "SARS-CoV"
    elif cn == 1:
        return "SARS-CoV-2"
    elif cn == 2:
        return "MERS-CoV"
    elif cn == 3:
        return "HCoV-229E"
    else:
        return "Boh"

In [3]:
@dataclass
class Event:
    """Improved feature of single event"""
    class_name: str
    amplitude: float
    d10: float
    d20: float
    d30: float
    d40: float
    d50: float
    d60: float
    d70: float
    d80: float
    d90: float
    c10: float
    c20: float
    c30: float
    c40: float
    c50: float
    c60: float
    c70: float
    c80: float
    c90: float

def event_as_list_no_class_name(e: Event):
    return [e.amplitude, 
            e.d10,e.d20, e.d30, e.d40, e.d50, e.d60, e.d70, e.d80, e.d90,
            e.c10,e.c20, e.c30, e.c40, e.c50, e.c60, e.c70, e.c80, e.c90]

In [51]:
# desktop_folder = os.path.join("C:\\", "Users", "Luca Rossi", "Desktop")
desktop_folder = os.path.join("/home", "luca", "Desktop")
results_folder = os.path.join(desktop_folder, "RESULTS")
virus_folders = ["SARS-CoV", "SARS-CoV-2", "MERS-CoV", "HCoV-229E"]
random_state = 69

def open_dat(filename):
    f = open(filename, "rb")
    f_cont = f.read()
    f.close()
    raw = struct.unpack("d" * (len(f_cont) // 8), f_cont)
    return np.array(raw)

def extract_lengths(filename):
    with open(filename) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        line_count = 0
        events_lengths = []
        for row in csv_reader:
            if len(row) > 1:
                if line_count > 1 and len(row) == 2:
                    events_lengths.append(int(row[1]) - int(row[0]))
            line_count+=1
        return events_lengths

def extract_raw_events(dir_name) -> List[ndarray]:
    events = []
    files = os.listdir(dir_name)
    if len(files) == 0:
        print(dir_name)
        return
    dat_file = [os.path.join(dir_name, f) for f in files if f.endswith(".dat")].pop()
    details_file = [os.path.join(dir_name, f) for f in files if f.endswith(".csv")].pop()
    # caricamento eventi dal singolo file    
    loaded_events = open_dat(dat_file)
    # caricamento dettagli file
    events_length = extract_lengths(details_file)  
    b = 0
    for ev_len in events_length:
        e = b + ev_len
        event = np.array(loaded_events[b:e])
        b = e
        events.append(event)
    return events

def duration_x_and_center(event: ndarray, baseline, amplitude, percentage):
    event = event - baseline
    event = np.concatenate(([0],event,[0]))
    event_x = np.nonzero(event < amplitude * (1 - percentage) )[0]
    dx = event_x.size
    if dx % 2 != 0:
        return dx, event_x[dx//2]
    m1 = dx // 2
    m0 = m1 - 1
    return dx, (event_x[m1] + event_x[m0]) / 2 
    
def calc_baseline(event: ndarray) -> float:
    ev_len = event.size
    x_baseline = np.concatenate((event[:round(ev_len/5*0.2)], event[round(ev_len - ev_len/5*0.2):]))
    return np.mean(x_baseline)

def extract_events(raw_events: List[ndarray], class_name) -> Tuple[str, List[Event]]:
    if raw_events is None:
        return []
    events = []
    for raw_event in raw_events:
        baseline = calc_baseline(raw_event)
#         remove last first and last 2/5 which are padding
        raw_event = raw_event[raw_event.size // 5 * 2:raw_event.size // 5 * 3]
        peak = raw_event.max()
        amplitude = peak-baseline
        d10, c10 = duration_x_and_center(raw_event, baseline, amplitude, 0.1)
        d20, c20 = duration_x_and_center(raw_event, baseline, amplitude, 0.2)
        d30, c30 = duration_x_and_center(raw_event, baseline, amplitude, 0.3)
        d40, c40 = duration_x_and_center(raw_event, baseline, amplitude, 0.4)
        d50, c50 = duration_x_and_center(raw_event, baseline, amplitude, 0.5)
        d60, c60 = duration_x_and_center(raw_event, baseline, amplitude, 0.6)
        d70, c70 = duration_x_and_center(raw_event, baseline, amplitude, 0.7)
        d80, c80 = duration_x_and_center(raw_event, baseline, amplitude, 0.8)
        d90, c90 = duration_x_and_center(raw_event, baseline, amplitude, 0.9)
        events.append(Event(class_name, amplitude,
                              d10, d20, d30, d40, d50, d60, d70, d80, d90,
                              c10, c20, c30, c40, c50, c60, c70, c80, c90))
    return events
        
def get_classes_and_paths(results_folder: List[str], virus_folders:List[str]):
    class_and_path_to_virus_dir = [ (v, os.path.join(results_folder, v)) for v in virus_folders]
    classes_and_paths = []
    for v, p in class_and_path_to_virus_dir:
        for new_p in [os.path.join(p, d) for d in os.listdir(p)]:
            classes_and_paths.append((v, new_p))            
    return classes_and_paths

def predict_entire_file(clf, events: List[Event]):
    results = {"SARS-CoV": 0, "SARS-CoV-2": 0, "MERS-CoV": 0, "HCoV-229E": 0}
    features = [event_as_list_no_class_name(e) for e in events]
    predictions = clf.predict(features)
    results["SARS-CoV"] = len([p for p in predictions if p == 0])
    results["SARS-CoV-2"] = len([p for p in predictions if p == 1])
    results["MERS-CoV"] = len([p for p in predictions if p == 2])
    results["HCoV-229E"] = len([p for p in predictions if p == 3])
    print(results)
    return max(results, key=results.get)

def get_test_and_train(c_p_e, idx, l):
    test = []
    c_p_e_without_test = [c_p_e[i] for i in range(len(c_p_e)) if i != idx]
    train = []
    for c in virus_folders:
        train_with_class_c = [(ct,_,e) for ct,_,e in c_p_e_without_test if ct == c]
        events = [item for sublist in [e for _, _, e in train_with_class_c] for item in sublist]
        events = shuffle(events, random_state=random_state)
        train+=events[:l]
        test.append((c,events[l:]))
    assert(l * 4 == len(train))
    train = shuffle(train,random_state=random_state)
    return test, train
    

def predict_entire_file_p_n(clf, events: List[Event]):
    results = {"Positive": 0, "Negative": 0}
    features = [event_as_list_no_class_name(e) for e in events]
    predictions = clf.predict(features)
    results["Positive"] = len([p for p in predictions if p == "Positive"])
    results["Negative"] = len([p for p in predictions if p == "Negative"])
    print(results)
    return max(results, key=results.get)

def predict_entire_file_p_n_svc(clf, scaler, events: List[Event]):
    results = {"Positive": 0, "Negative": 0}
    features = [event_as_list_no_class_name(e) for e in events]
    features = scaler.transform(features)
    predictions = clf.predict_proba(features)
    print(predictions)
    results["Positive"] = len([p for p in predictions if p == "Positive"])
    results["Negative"] = len([p for p in predictions if p == "Negative"])
    print(results)
    return max(results, key=results.get)

In [5]:
c_p = get_classes_and_paths(results_folder, virus_folders)
c_p_re = [ (c, p, extract_raw_events(p)) for c, p in c_p]
c_p_e = [(c, p, extract_events(re, c)) for c, p, re in c_p_re]

In [6]:
confusion_matrix_with_balanced_training_data_and_leftovers = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
# |test| = |train * 4|
confusion_matrix_balanced_training_data = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
clf = RandomForestClassifier(class_weight="balanced_subsample", random_state=random_state)
for idx in range(len(c_p_e)):
    print("CICLO ", idx)
    test_class, _, test_events = c_p_e[idx]
    test, train = get_test_and_train(c_p_e, idx, len(test_events))
    classes = [class_name_to_numeric(e.class_name) for e in train]
    features = [event_as_list_no_class_name(e) for e in train]
    clf.fit(features, classes)
    print(test_class)
    prediction = predict_entire_file(clf, test_events)
    confusion_matrix_balanced_training_data[class_name_to_numeric(test_class)][class_name_to_numeric(prediction)] += 1    
    print("others")
    for tc,te in test:
        print(tc)
        prediction = predict_entire_file(clf, te)
        confusion_matrix_with_balanced_training_data_and_leftovers[class_name_to_numeric(tc)][class_name_to_numeric(prediction)] += 1
    print("----------------------")

CICLO  0
SARS-CoV
{'SARS-CoV': 72, 'SARS-CoV-2': 7, 'MERS-CoV': 6, 'HCoV-229E': 6}
others
SARS-CoV
{'SARS-CoV': 471, 'SARS-CoV-2': 98, 'MERS-CoV': 136, 'HCoV-229E': 134}
SARS-CoV-2
{'SARS-CoV': 148, 'SARS-CoV-2': 518, 'MERS-CoV': 89, 'HCoV-229E': 155}
MERS-CoV
{'SARS-CoV': 175, 'SARS-CoV-2': 88, 'MERS-CoV': 237, 'HCoV-229E': 134}
HCoV-229E
{'SARS-CoV': 281, 'SARS-CoV-2': 288, 'MERS-CoV': 335, 'HCoV-229E': 806}
----------------------
CICLO  1
SARS-CoV
{'SARS-CoV': 93, 'SARS-CoV-2': 55, 'MERS-CoV': 65, 'HCoV-229E': 39}
others
SARS-CoV
{'SARS-CoV': 297, 'SARS-CoV-2': 54, 'MERS-CoV': 106, 'HCoV-229E': 60}
SARS-CoV-2
{'SARS-CoV': 82, 'SARS-CoV-2': 468, 'MERS-CoV': 88, 'HCoV-229E': 111}
MERS-CoV
{'SARS-CoV': 95, 'SARS-CoV-2': 77, 'MERS-CoV': 202, 'HCoV-229E': 99}
HCoV-229E
{'SARS-CoV': 216, 'SARS-CoV-2': 269, 'MERS-CoV': 240, 'HCoV-229E': 824}
----------------------
CICLO  2
SARS-CoV
{'SARS-CoV': 149, 'SARS-CoV-2': 8, 'MERS-CoV': 30, 'HCoV-229E': 25}
others
SARS-CoV
{'SARS-CoV': 337, 'SARS-C

HCoV-229E
{'SARS-CoV': 43, 'SARS-CoV-2': 36, 'MERS-CoV': 36, 'HCoV-229E': 148}
others
SARS-CoV
{'SARS-CoV': 412, 'SARS-CoV-2': 75, 'MERS-CoV': 162, 'HCoV-229E': 109}
SARS-CoV-2
{'SARS-CoV': 114, 'SARS-CoV-2': 430, 'MERS-CoV': 89, 'HCoV-229E': 105}
MERS-CoV
{'SARS-CoV': 114, 'SARS-CoV-2': 69, 'MERS-CoV': 178, 'HCoV-229E': 101}
HCoV-229E
{'SARS-CoV': 188, 'SARS-CoV-2': 235, 'MERS-CoV': 214, 'HCoV-229E': 638}
----------------------
CICLO  20
HCoV-229E
{'SARS-CoV': 48, 'SARS-CoV-2': 56, 'MERS-CoV': 45, 'HCoV-229E': 250}
others
SARS-CoV
{'SARS-CoV': 353, 'SARS-CoV-2': 82, 'MERS-CoV': 108, 'HCoV-229E': 79}
SARS-CoV-2
{'SARS-CoV': 84, 'SARS-CoV-2': 371, 'MERS-CoV': 71, 'HCoV-229E': 76}
MERS-CoV
{'SARS-CoV': 80, 'SARS-CoV-2': 54, 'MERS-CoV': 134, 'HCoV-229E': 58}
HCoV-229E
{'SARS-CoV': 132, 'SARS-CoV-2': 195, 'MERS-CoV': 192, 'HCoV-229E': 484}
----------------------
CICLO  21
HCoV-229E
{'SARS-CoV': 10, 'SARS-CoV-2': 17, 'MERS-CoV': 8, 'HCoV-229E': 9}
others
SARS-CoV
{'SARS-CoV': 519, 'SARS-CoV

In [7]:
print(np.array(confusion_matrix_balanced_training_data))
print(np.array(confusion_matrix_with_balanced_training_data_and_leftovers))

[[5 0 0 0]
 [0 3 0 0]
 [3 0 3 0]
 [1 2 2 7]]
[[26  0  0  0]
 [ 0 25  0  1]
 [ 2  0 24  0]
 [ 0  1  0 25]]


# Saliva

In [8]:
training_folder = os.path.join(desktop_folder, "TRAINING")
test_folder = os.path.join(desktop_folder, "TEST")
positive_negative_folders =["Positive", "Negative"]

# Extract training data and train model

In [9]:
c_p_saliva_train = get_classes_and_paths(training_folder, positive_negative_folders)
c_p_re_saliva_train = [ (c, p, extract_raw_events(p)) for c, p in c_p_saliva_train]
c_p_e_saliva_train = [(c, p, extract_events(re, c)) for c, p, re in c_p_re_saliva_train]
print(len(c_p_e_saliva_train))
print([p for _, p, e in c_p_e_saliva_train if len(e)==0])
c_p_e_saliva_train = [(c, p, e) for c, p, e in c_p_e_saliva_train if len(e)>0]
print(len(c_p_e_saliva_train))


c_p_saliva_test = get_classes_and_paths(test_folder, positive_negative_folders)
c_p_re_saliva_test = [ (c, p, extract_raw_events(p)) for c, p in c_p_saliva_test]
c_p_e_saliva_test = [(c, p, extract_events(re, c)) for c, p, re in c_p_re_saliva_test]
print(len(c_p_e_saliva_test))
c_p_e_saliva_test = [(c, p, e) for c, p, e in c_p_e_saliva_test if len(e)>0]
print(len(c_p_e_saliva_test))


/home/luca/Desktop/TRAINING/Positive/F8 day1
/home/luca/Desktop/TRAINING/Positive/AS-2-2-bias+01_BK-953_045fil_TI_1st
/home/luca/Desktop/TRAINING/Positive/AS-2-2-bias+01_BK-1126_045fil_TI
/home/luca/Desktop/TRAINING/Positive/F2
/home/luca/Desktop/TRAINING/Negative/HD-120420-17
/home/luca/Desktop/TRAINING/Negative/HD-112720-58
/home/luca/Desktop/TRAINING/Negative/HD-120720-6
/home/luca/Desktop/TRAINING/Negative/HD-120420-33
/home/luca/Desktop/TRAINING/Negative/HD-120420-44
/home/luca/Desktop/TRAINING/Negative/HD-112720-46
/home/luca/Desktop/TRAINING/Negative/HD-120720-46
/home/luca/Desktop/TRAINING/Negative/HD-120420-32
80
['/home/luca/Desktop/TRAINING/Positive/F8 day1', '/home/luca/Desktop/TRAINING/Positive/AS-2-2-bias+01_BK-953_045fil_TI_1st', '/home/luca/Desktop/TRAINING/Positive/AS-2-2-bias+01_BK-1126_045fil_TI', '/home/luca/Desktop/TRAINING/Positive/F2', '/home/luca/Desktop/TRAINING/Negative/HD-120420-17', '/home/luca/Desktop/TRAINING/Negative/HD-112720-58', '/home/luca/Desktop/TRA

In [46]:
positive_events = [item for sublist in [e for ct,_,e in c_p_e_saliva_train if ct == "Positive"] for item in sublist]
negetive_events = [item for sublist in [e for ct,_,e in c_p_e_saliva_train if ct == "Negative"] for item in sublist]
print(len(positive_events))
print(len(negetive_events))

15034
9336


In [47]:
positive_events = shuffle(positive_events, random_state=random_state)
# get only subset of positive events to make it more balanced
positive_events = positive_events[:len(negetive_events)]
print(len(positive_events))
print(len(negetive_events))

9336
9336


In [48]:
train = positive_events+negetive_events
train = shuffle(train, random_state=random_state)
train_labels = [e.class_name for e in train]
train_X = [event_as_list_no_class_name(e) for e in train]
train_X = np.array(train_X)

## Train classifier

In [13]:
from sklearn.model_selection import RandomizedSearchCV
from pprint import pprint
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

pprint(random_grid)

{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}


In [14]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier(random_state = 69)
# Random search of parameters, using 5 fold cross validation, 
# search across 100 different combinations, and use all available cores
cv = train_X.size
rf_random = RandomizedSearchCV(estimator=rf, param_distributions=random_grid,
                              n_iter = 100, cv = 10, verbose=2, random_state=69, 
                              n_jobs=-1, return_train_score=True)

# Fit the random search model
rf_random.fit(train_X, train_labels)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


RandomizedSearchCV(cv=10, estimator=RandomForestClassifier(random_state=69),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=69, return_train_score=True, verbose=2)

In [15]:
rf_random.best_params_

{'n_estimators': 800,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_depth': 10,
 'bootstrap': False}

In [21]:
saliva_classifier = RandomForestClassifier(random_state=random_state, n_estimators=800, min_samples_split=5, min_samples_leaf=1,max_depth=10,bootstrap=True, oob_score=True)
saliva_classifier.fit(train_X, train_labels)
print(saliva_classifier.oob_score_)

0.5318658954584404


## Test classifier

In [19]:
saliva_confusion_matrix = [[0,0],[0,0]]
for tc,_,te in c_p_e_saliva_test:
    print(tc)
    prediction = predict_entire_file_p_n(saliva_classifier, te)
    saliva_confusion_matrix[class_name_to_numeric_p_n(tc)][class_name_to_numeric_p_n(prediction)] += 1

Positive
{'Positive': 703, 'Negative': 508}
Positive
{'Positive': 589, 'Negative': 320}
Positive
{'Positive': 25, 'Negative': 24}
Positive
{'Positive': 161, 'Negative': 205}
Positive
{'Positive': 58, 'Negative': 206}
Positive
{'Positive': 421, 'Negative': 772}
Positive
{'Positive': 52, 'Negative': 60}
Positive
{'Positive': 524, 'Negative': 482}
Positive
{'Positive': 92, 'Negative': 125}
Positive
{'Positive': 227, 'Negative': 213}
Positive
{'Positive': 111, 'Negative': 199}
Positive
{'Positive': 79, 'Negative': 104}
Positive
{'Positive': 137, 'Negative': 283}
Positive
{'Positive': 91, 'Negative': 99}
Positive
{'Positive': 111, 'Negative': 54}
Positive
{'Positive': 82, 'Negative': 87}
Positive
{'Positive': 63, 'Negative': 160}
Positive
{'Positive': 835, 'Negative': 541}
Positive
{'Positive': 150, 'Negative': 142}
Positive
{'Positive': 145, 'Negative': 71}
Positive
{'Positive': 42, 'Negative': 48}
Positive
{'Positive': 172, 'Negative': 116}
Positive
{'Positive': 22, 'Negative': 31}
Positi

In [18]:
np.array(saliva_confusion_matrix)

array([[19, 23],
       [28, 19]])

# Testing out another method to ensemble results and using a different classifier

# Preprocessing data: Standardization

In [49]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(train_X)
std_train_X = scaler.transform(train_X)
# REMEMBER TO PREPROCESS TEST DATA TOO

## Grid search for svm

In [53]:
kernel = ["linear", "poly", "rbf", "sigmoid", "precomputed"]
degree = [1,3,5]

random_grid_svc = {'kernel': kernel,
                   'degree': degree}

In [ ]:
cv = train_X.size
svc = SVC(probability=True, random_state=random_state)
svc_random = GridSearchCV(svc, random_grid_svc)

# Fit the random search model
svc_random.fit(train_X, train_labels)

## Train SVM

In [50]:
from sklearn.svm import SVC
svc = SVC(probability=True, random_state=random_state)
svc.fit(std_train_X, train_labels)

SVC(probability=True)

## Test svm

In [52]:
saliva_confusion_matrix_svc = [[0,0],[0,0]]
for tc,_,te in c_p_e_saliva_test:
    print(tc)
    prediction = predict_entire_file_p_n_svc(svc, scaler, te)
    saliva_confusion_matrix_svc[class_name_to_numeric_p_n(tc)][class_name_to_numeric_p_n(prediction)] += 1

Positive
[[0.52462501 0.47537499]
 [0.5469997  0.4530003 ]
 [0.52020325 0.47979675]
 [0.58986281 0.41013719]
 [0.51870564 0.48129436]
 [0.50640184 0.49359816]
 [0.52552689 0.47447311]
 [0.4786501  0.5213499 ]
 [0.5648397  0.4351603 ]
 [0.403517   0.596483  ]
 [0.52972918 0.47027082]
 [0.47763744 0.52236256]
 [0.45824897 0.54175103]
 [0.48372847 0.51627153]
 [0.46198477 0.53801523]
 [0.56542558 0.43457442]
 [0.4033154  0.5966846 ]
 [0.51201729 0.48798271]
 [0.4704788  0.5295212 ]
 [0.42571893 0.57428107]
 [0.53486406 0.46513594]
 [0.49386702 0.50613298]
 [0.56108371 0.43891629]
 [0.46862961 0.53137039]
 [0.47317743 0.52682257]
 [0.45441746 0.54558254]
 [0.4706837  0.5293163 ]
 [0.44546211 0.55453789]
 [0.42320888 0.57679112]
 [0.56419006 0.43580994]
 [0.52672987 0.47327013]
 [0.55671624 0.44328376]
 [0.45636589 0.54363411]
 [0.48429211 0.51570789]
 [0.5        0.5       ]
 [0.46571311 0.53428689]
 [0.50581894 0.49418106]
 [0.5        0.5       ]
 [0.48078374 0.51921626]
 [0.51045059 0.4

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.40914867 0.59085133]
 [0.51486989 0.48513011]
 [0.43533995 0.56466005]
 ...
 [0.43986292 0.56013708]
 [0.46255703 0.53744297]
 [0.51920851 0.48079149]]
{'Positive': 0, 'Negative': 0}
Positive
[[0.55711535 0.44288465]
 [0.56639628 0.43360372]
 [0.58864327 0.41135673]
 [0.54792101 0.45207899]
 [0.52746613 0.47253387]
 [0.58308469 0.41691531]
 [0.56872112 0.43127888]
 [0.53842217 0.46157783]
 [0.5482303  0.4517697 ]
 [0.58378781 0.41621219]
 [0.5835221  0.4164779 ]
 [0.48716659 0.51283341]
 [0.54111636 0.45888364]
 [0.52830651 0.47169349]
 [0.54289986 0.45710014]
 [0.55572294 0.44427706]
 [0.5640804  0.4359196 ]
 [0.52065352 0.47934648]
 [0.54067208 0.45932792]
 [0.57698363 0.42301637]
 [0.51060079 0.48939921]
 [0.51622523 0.48377477]
 [0.52160642 0.47839358]
 [0.5505478  0.4494522 ]
 [0.58803159 0.41196841]
 [0.51359061 0.48640939]
 [0.5        0.5       ]
 [0.5985946  0.4014054 ]
 [0.55931318 0.44068682]
 [0.52200086 0.47799914]
 [0.45576666 0.54423334]
 [0.58113019 0.41886981]
 [0.

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.52351872 0.47648128]
 [0.4245996  0.5754004 ]
 [0.47679611 0.52320389]
 ...
 [0.5297531  0.4702469 ]
 [0.49408171 0.50591829]
 [0.53446226 0.46553774]]
{'Positive': 0, 'Negative': 0}
Positive
[[0.55455006 0.44544994]
 [0.4218108  0.5781892 ]
 [0.5        0.5       ]
 [0.51253632 0.48746368]
 [0.5        0.5       ]
 [0.5252437  0.4747563 ]
 [0.55682269 0.44317731]
 [0.54376535 0.45623465]
 [0.51188995 0.48811005]
 [0.51369431 0.48630569]
 [0.5        0.5       ]
 [0.51602293 0.48397707]
 [0.51637045 0.48362955]
 [0.57415557 0.42584443]
 [0.5        0.5       ]
 [0.43017969 0.56982031]
 [0.50769655 0.49230345]
 [0.57129435 0.42870565]
 [0.44946763 0.55053237]
 [0.45797128 0.54202872]
 [0.53670663 0.46329337]
 [0.45053461 0.54946539]
 [0.55421093 0.44578907]
 [0.53330405 0.46669595]
 [0.49106025 0.50893975]
 [0.56989378 0.43010622]
 [0.52261926 0.47738074]
 [0.53925357 0.46074643]
 [0.40322292 0.59677708]
 [0.53842979 0.46157021]
 [0.53026414 0.46973586]
 [0.4625666  0.5374334 ]
 [0.

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.41053463 0.58946537]
 [0.59755701 0.40244299]
 [0.53623801 0.46376199]
 [0.52200657 0.47799343]
 [0.53299305 0.46700695]
 [0.56786482 0.43213518]
 [0.5737329  0.4262671 ]
 [0.46008912 0.53991088]
 [0.53016133 0.46983867]
 [0.60513224 0.39486776]
 [0.47463276 0.52536724]
 [0.58850164 0.41149836]
 [0.54482753 0.45517247]
 [0.51083318 0.48916682]
 [0.53051753 0.46948247]
 [0.53663881 0.46336119]
 [0.48906314 0.51093686]
 [0.52388981 0.47611019]
 [0.53787788 0.46212212]
 [0.58203116 0.41796884]
 [0.5        0.5       ]
 [0.39580898 0.60419102]
 [0.41189585 0.58810415]
 [0.54976814 0.45023186]
 [0.53813945 0.46186055]
 [0.56676084 0.43323916]
 [0.57128123 0.42871877]
 [0.54508972 0.45491028]
 [0.53242116 0.46757884]
 [0.53758344 0.46241656]
 [0.44136163 0.55863837]
 [0.48699687 0.51300313]
 [0.56121356 0.43878644]
 [0.56597724 0.43402276]
 [0.55148202 0.44851798]
 [0.52724747 0.47275253]
 [0.58648137 0.41351863]
 [0.57154099 0.42845901]
 [0.57485936 0.42514064]
 [0.50519063 0.49480937]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.48210795 0.51789205]
 [0.50797862 0.49202138]
 [0.4906249  0.5093751 ]
 ...
 [0.5        0.5       ]
 [0.48879816 0.51120184]
 [0.40817861 0.59182139]]
{'Positive': 0, 'Negative': 0}
Positive
[[0.45692549 0.54307451]
 [0.5        0.5       ]
 [0.48131087 0.51868913]
 [0.5780955  0.4219045 ]
 [0.48648509 0.51351491]
 [0.45262423 0.54737577]
 [0.52085688 0.47914312]
 [0.48438098 0.51561902]
 [0.51785992 0.48214008]
 [0.5102428  0.4897572 ]
 [0.56289566 0.43710434]
 [0.52552722 0.47447278]
 [0.56040577 0.43959423]
 [0.46994762 0.53005238]
 [0.42302094 0.57697906]
 [0.48130569 0.51869431]
 [0.42544914 0.57455086]
 [0.55481766 0.44518234]
 [0.53594074 0.46405926]
 [0.55415568 0.44584432]
 [0.52791705 0.47208295]
 [0.55680646 0.44319354]
 [0.52483731 0.47516269]
 [0.53301209 0.46698791]
 [0.5152654  0.4847346 ]
 [0.57654483 0.42345517]
 [0.54755787 0.45244213]
 [0.55023647 0.44976353]
 [0.55516417 0.44483583]
 [0.50948687 0.49051313]
 [0.5299021  0.4700979 ]
 [0.56124896 0.43875104]
 [0.

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.43410685 0.56589315]
 [0.5        0.5       ]
 [0.53575435 0.46424565]
 [0.52095804 0.47904196]
 [0.46980435 0.53019565]
 [0.51412973 0.48587027]
 [0.53962787 0.46037213]
 [0.56140537 0.43859463]
 [0.47846861 0.52153139]
 [0.49177959 0.50822041]
 [0.42637897 0.57362103]
 [0.58368245 0.41631755]
 [0.4927562  0.5072438 ]
 [0.53424751 0.46575249]
 [0.56988563 0.43011437]
 [0.48189146 0.51810854]
 [0.58570223 0.41429777]
 [0.36685709 0.63314291]
 [0.42734717 0.57265283]
 [0.47680296 0.52319704]
 [0.49389159 0.50610841]
 [0.51229201 0.48770799]
 [0.56977955 0.43022045]
 [0.49016312 0.50983688]
 [0.51044216 0.48955784]
 [0.5        0.5       ]
 [0.47915506 0.52084494]
 [0.48115128 0.51884872]
 [0.46365656 0.53634344]
 [0.44757691 0.55242309]
 [0.48837899 0.51162101]
 [0.47502745 0.52497255]
 [0.46200871 0.53799129]
 [0.46612062 0.53387938]
 [0.5153425  0.4846575 ]
 [0.51253615 0.48746385]
 [0.47460096 0.52539904]
 [0.51867654 0.48132346]
 [0.53728546 0.46271454]
 [0.55987834 0.44012166]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.57877548 0.42122452]
 [0.45612601 0.54387399]
 [0.43773864 0.56226136]
 [0.5        0.5       ]
 [0.56740513 0.43259487]
 [0.55625686 0.44374314]
 [0.56087965 0.43912035]
 [0.56029159 0.43970841]
 [0.43074528 0.56925472]
 [0.52256284 0.47743716]
 [0.53980678 0.46019322]
 [0.49464896 0.50535104]
 [0.48327414 0.51672586]
 [0.55159885 0.44840115]
 [0.54243655 0.45756345]
 [0.54873941 0.45126059]
 [0.5        0.5       ]
 [0.54483824 0.45516176]
 [0.5        0.5       ]
 [0.48334444 0.51665556]
 [0.47390371 0.52609629]
 [0.48745244 0.51254756]
 [0.56462666 0.43537334]
 [0.52869712 0.47130288]
 [0.51429058 0.48570942]
 [0.55531102 0.44468898]
 [0.54089026 0.45910974]
 [0.4158899  0.5841101 ]
 [0.48261137 0.51738863]
 [0.49430886 0.50569114]
 [0.57683969 0.42316031]
 [0.54477391 0.45522609]
 [0.52739813 0.47260187]
 [0.57768248 0.42231752]
 [0.55310801 0.44689199]
 [0.56378473 0.43621527]
 [0.5212848  0.4787152 ]
 [0.57252285 0.42747715]
 [0.50569886 0.49430114]
 [0.49391254 0.50608746]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.41743652 0.58256348]]
{'Positive': 0, 'Negative': 0}
Positive
[[0.48304531 0.51695469]
 [0.57738695 0.42261305]
 [0.51880237 0.48119763]
 [0.48483045 0.51516955]
 [0.43851604 0.56148396]]
{'Positive': 0, 'Negative': 0}
Positive


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.41661933 0.58338067]
 [0.48325759 0.51674241]
 [0.43659318 0.56340682]
 ...
 [0.47069853 0.52930147]
 [0.38346827 0.61653173]
 [0.45018583 0.54981417]]
{'Positive': 0, 'Negative': 0}
Positive
[[0.54146043 0.45853957]
 [0.5        0.5       ]
 [0.57203745 0.42796255]
 [0.5755711  0.4244289 ]
 [0.5        0.5       ]
 [0.50628206 0.49371794]
 [0.56190119 0.43809881]
 [0.52461444 0.47538556]
 [0.57294378 0.42705622]
 [0.53290908 0.46709092]
 [0.5751461  0.4248539 ]
 [0.53888769 0.46111231]
 [0.47602023 0.52397977]
 [0.56747522 0.43252478]
 [0.55782051 0.44217949]
 [0.47728998 0.52271002]
 [0.5731711  0.4268289 ]
 [0.46314255 0.53685745]
 [0.47852825 0.52147175]
 [0.55951202 0.44048798]
 [0.52692094 0.47307906]
 [0.48972873 0.51027127]
 [0.51049842 0.48950158]
 [0.48483908 0.51516092]]
{'Positive': 0, 'Negative': 0}
Positive


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.48271757 0.51728243]
 [0.4847439  0.5152561 ]
 [0.50748334 0.49251666]
 ...
 [0.38108346 0.61891654]
 [0.51384688 0.48615312]
 [0.46810912 0.53189088]]
{'Positive': 0, 'Negative': 0}
Positive


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.55668467 0.44331533]
 [0.5117752  0.4882248 ]
 [0.558395   0.441605  ]
 [0.57043392 0.42956608]
 [0.45170194 0.54829806]
 [0.56464022 0.43535978]
 [0.54407636 0.45592364]
 [0.47285818 0.52714182]
 [0.55727743 0.44272257]
 [0.54135183 0.45864817]
 [0.52519731 0.47480269]
 [0.57452232 0.42547768]
 [0.56155888 0.43844112]
 [0.55665947 0.44334053]
 [0.5537887  0.4462113 ]
 [0.5235792  0.4764208 ]
 [0.53239909 0.46760091]
 [0.53980692 0.46019308]
 [0.54675713 0.45324287]
 [0.56882525 0.43117475]
 [0.5        0.5       ]
 [0.51820743 0.48179257]
 [0.57145013 0.42854987]
 [0.54444246 0.45555754]
 [0.59474305 0.40525695]
 [0.58640795 0.41359205]
 [0.47256271 0.52743729]
 [0.55203066 0.44796934]
 [0.5341319  0.4658681 ]
 [0.55132172 0.44867828]
 [0.55344308 0.44655692]
 [0.52918753 0.47081247]
 [0.50701698 0.49298302]
 [0.53123979 0.46876021]
 [0.56566665 0.43433335]
 [0.55532855 0.44467145]
 [0.56939799 0.43060201]
 [0.52256627 0.47743373]
 [0.509157   0.490843  ]
 [0.56236331 0.43763669]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.51545435 0.48454565]
 [0.56135722 0.43864278]
 [0.57774173 0.42225827]
 [0.40986985 0.59013015]
 [0.55047069 0.44952931]
 [0.58158982 0.41841018]
 [0.51392976 0.48607024]
 [0.5        0.5       ]
 [0.54436471 0.45563529]
 [0.58480067 0.41519933]
 [0.47738532 0.52261468]
 [0.5721249  0.4278751 ]
 [0.52810532 0.47189468]
 [0.53693425 0.46306575]
 [0.47173303 0.52826697]
 [0.40858846 0.59141154]
 [0.55801923 0.44198077]
 [0.51810243 0.48189757]
 [0.53727075 0.46272925]
 [0.40922817 0.59077183]
 [0.39010805 0.60989195]
 [0.57120507 0.42879493]
 [0.48553953 0.51446047]
 [0.51853708 0.48146292]
 [0.55361937 0.44638063]
 [0.54893877 0.45106123]
 [0.47210571 0.52789429]
 [0.51968037 0.48031963]
 [0.51573252 0.48426748]
 [0.52133283 0.47866717]
 [0.55627727 0.44372273]
 [0.5        0.5       ]
 [0.53842485 0.46157515]
 [0.56437914 0.43562086]
 [0.52493652 0.47506348]
 [0.54734421 0.45265579]
 [0.51293149 0.48706851]
 [0.53297726 0.46702274]
 [0.53681254 0.46318746]
 [0.51018972 0.48981028]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.41064196 0.58935804]
 [0.54404952 0.45595048]
 [0.5        0.5       ]
 [0.54134018 0.45865982]
 [0.47882644 0.52117356]
 [0.48639419 0.51360581]
 [0.48171423 0.51828577]
 [0.45493004 0.54506996]
 [0.48539029 0.51460971]
 [0.57419301 0.42580699]
 [0.48928411 0.51071589]
 [0.53454432 0.46545568]
 [0.52644979 0.47355021]
 [0.46754111 0.53245889]
 [0.4120661  0.5879339 ]
 [0.49006682 0.50993318]
 [0.5754923  0.4245077 ]
 [0.53482971 0.46517029]
 [0.50959505 0.49040495]
 [0.52679029 0.47320971]
 [0.46819481 0.53180519]
 [0.41268003 0.58731997]
 [0.45847773 0.54152227]
 [0.54777837 0.45222163]
 [0.45774829 0.54225171]
 [0.44628376 0.55371624]
 [0.49163834 0.50836166]
 [0.51874598 0.48125402]
 [0.4850709  0.5149291 ]
 [0.48619542 0.51380458]
 [0.53989681 0.46010319]
 [0.47472056 0.52527944]
 [0.45744932 0.54255068]
 [0.51586989 0.48413011]
 [0.56492704 0.43507296]
 [0.44662421 0.55337579]
 [0.5        0.5       ]
 [0.53528145 0.46471855]
 [0.54305205 0.45694795]
 [0.45049292 0.54950708]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.52756856 0.47243144]
 [0.5432526  0.4567474 ]
 [0.43967377 0.56032623]
 [0.47013179 0.52986821]
 [0.48353636 0.51646364]
 [0.4747856  0.5252144 ]
 [0.46062887 0.53937113]
 [0.43624046 0.56375954]
 [0.5        0.5       ]
 [0.51504881 0.48495119]
 [0.5        0.5       ]
 [0.57345004 0.42654996]
 [0.42440448 0.57559552]
 [0.48003115 0.51996885]
 [0.53063971 0.46936029]
 [0.55922839 0.44077161]
 [0.51276709 0.48723291]
 [0.5        0.5       ]
 [0.5731364  0.4268636 ]
 [0.43290925 0.56709075]
 [0.59406035 0.40593965]
 [0.5        0.5       ]
 [0.52997581 0.47002419]
 [0.57361657 0.42638343]
 [0.47618145 0.52381855]
 [0.53664874 0.46335126]
 [0.5        0.5       ]
 [0.44381494 0.55618506]
 [0.55771562 0.44228438]
 [0.51983786 0.48016214]
 [0.55205246 0.44794754]
 [0.53055939 0.46944061]
 [0.55758543 0.44241457]
 [0.46242864 0.53757136]
 [0.55277709 0.44722291]
 [0.46959025 0.53040975]
 [0.5127217  0.4872783 ]
 [0.44716174 0.55283826]
 [0.52872238 0.47127762]
 [0.55604035 0.44395965]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.48119835 0.51880165]
 [0.52761445 0.47238555]
 [0.49239428 0.50760572]
 ...
 [0.46122637 0.53877363]
 [0.46587955 0.53412045]
 [0.52939648 0.47060352]]
{'Positive': 0, 'Negative': 0}
Positive
[[0.51908769 0.48091231]
 [0.5        0.5       ]
 [0.56921671 0.43078329]
 [0.4496735  0.5503265 ]
 [0.50825772 0.49174228]
 [0.55506945 0.44493055]
 [0.42585867 0.57414133]
 [0.4407387  0.5592613 ]
 [0.44654904 0.55345096]
 [0.47544172 0.52455828]
 [0.54618674 0.45381326]
 [0.45697634 0.54302366]
 [0.39912955 0.60087045]
 [0.47436691 0.52563309]
 [0.44038043 0.55961957]
 [0.41503805 0.58496195]
 [0.43635854 0.56364146]
 [0.43360873 0.56639127]
 [0.43021808 0.56978192]
 [0.39632708 0.60367292]
 [0.43991013 0.56008987]
 [0.5        0.5       ]
 [0.45104485 0.54895515]
 [0.48779626 0.51220374]
 [0.47890049 0.52109951]
 [0.51182389 0.48817611]
 [0.42324065 0.57675935]
 [0.52208133 0.47791867]
 [0.48852071 0.51147929]
 [0.47025034 0.52974966]
 [0.48248072 0.51751928]
 [0.47833407 0.52166593]
 [0.

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.50901641 0.49098359]
 [0.55906553 0.44093447]
 [0.55772386 0.44227614]
 [0.57021629 0.42978371]
 [0.5146937  0.4853063 ]
 [0.43623734 0.56376266]
 [0.52102468 0.47897532]
 [0.5594497  0.4405503 ]
 [0.47440626 0.52559374]
 [0.45975065 0.54024935]
 [0.54853148 0.45146852]
 [0.57703865 0.42296135]
 [0.51434084 0.48565916]
 [0.50560237 0.49439763]
 [0.57247902 0.42752098]
 [0.57848427 0.42151573]
 [0.52903493 0.47096507]
 [0.46572785 0.53427215]
 [0.54825004 0.45174996]
 [0.55140971 0.44859029]
 [0.53665067 0.46334933]
 [0.57746406 0.42253594]
 [0.51091599 0.48908401]
 [0.58303547 0.41696453]
 [0.4834511  0.5165489 ]
 [0.48950708 0.51049292]
 [0.49275822 0.50724178]
 [0.51425672 0.48574328]
 [0.54353781 0.45646219]
 [0.5061292  0.4938708 ]
 [0.53826969 0.46173031]
 [0.55177163 0.44822837]
 [0.58084136 0.41915864]
 [0.57175584 0.42824416]
 [0.52469961 0.47530039]
 [0.54667895 0.45332105]
 [0.53783585 0.46216415]
 [0.56927618 0.43072382]
 [0.5778688  0.4221312 ]
 [0.5293971  0.4706029 ]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.56065117 0.43934883]
 [0.54116398 0.45883602]
 [0.55731515 0.44268485]
 ...
 [0.54195178 0.45804822]
 [0.5        0.5       ]
 [0.56756222 0.43243778]]
{'Positive': 0, 'Negative': 0}
Positive


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.52438582 0.47561418]
 [0.55135705 0.44864295]
 [0.54019841 0.45980159]
 [0.54053315 0.45946685]
 [0.50653144 0.49346856]
 [0.45774604 0.54225396]
 [0.50955563 0.49044437]
 [0.5        0.5       ]
 [0.50947838 0.49052162]
 [0.52219848 0.47780152]
 [0.51404968 0.48595032]
 [0.56479565 0.43520435]
 [0.55589326 0.44410674]
 [0.5        0.5       ]
 [0.57602206 0.42397794]
 [0.56729655 0.43270345]
 [0.43601576 0.56398424]
 [0.51460199 0.48539801]
 [0.52297746 0.47702254]
 [0.5541961  0.4458039 ]
 [0.56042195 0.43957805]
 [0.49008508 0.50991492]
 [0.43037384 0.56962616]
 [0.5        0.5       ]
 [0.56219888 0.43780112]
 [0.50549753 0.49450247]
 [0.46526302 0.53473698]
 [0.46669438 0.53330562]
 [0.53435821 0.46564179]
 [0.47842738 0.52157262]
 [0.43359898 0.56640102]
 [0.53094026 0.46905974]
 [0.49132724 0.50867276]
 [0.46528868 0.53471132]
 [0.50998626 0.49001374]
 [0.52683613 0.47316387]
 [0.44431632 0.55568368]
 [0.5        0.5       ]
 [0.51720086 0.48279914]
 [0.54461779 0.45538221]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.54699664 0.45300336]
 [0.42185101 0.57814899]
 [0.46783358 0.53216642]
 [0.55334077 0.44665923]
 [0.44413504 0.55586496]
 [0.5        0.5       ]
 [0.51563785 0.48436215]
 [0.5778889  0.4221111 ]
 [0.51884378 0.48115622]
 [0.52028125 0.47971875]
 [0.48457788 0.51542212]
 [0.52825321 0.47174679]
 [0.43265203 0.56734797]
 [0.52913932 0.47086068]
 [0.52540285 0.47459715]
 [0.5184313  0.4815687 ]
 [0.52579265 0.47420735]
 [0.5        0.5       ]
 [0.50913482 0.49086518]
 [0.56580819 0.43419181]
 [0.54772652 0.45227348]
 [0.42389192 0.57610808]
 [0.39286059 0.60713941]
 [0.43667264 0.56332736]
 [0.48318175 0.51681825]
 [0.51767618 0.48232382]
 [0.54385721 0.45614279]
 [0.53558875 0.46441125]
 [0.59279168 0.40720832]
 [0.56903395 0.43096605]
 [0.43728597 0.56271403]
 [0.56456168 0.43543832]
 [0.48318509 0.51681491]
 [0.53587193 0.46412807]
 [0.54367435 0.45632565]
 [0.48778874 0.51221126]
 [0.5        0.5       ]
 [0.52379435 0.47620565]
 [0.55816072 0.44183928]
 [0.55632909 0.44367091]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.42337704 0.57662296]
 [0.54816005 0.45183995]
 [0.38415604 0.61584396]
 [0.42054118 0.57945882]
 [0.44407133 0.55592867]
 [0.3858333  0.6141667 ]
 [0.40501885 0.59498115]
 [0.4939748  0.5060252 ]
 [0.56616633 0.43383367]
 [0.51220841 0.48779159]
 [0.55564803 0.44435197]
 [0.54494463 0.45505537]
 [0.44586443 0.55413557]
 [0.43540347 0.56459653]
 [0.40750077 0.59249923]
 [0.37949885 0.62050115]
 [0.52866826 0.47133174]
 [0.52259657 0.47740343]
 [0.57302896 0.42697104]
 [0.54163666 0.45836334]
 [0.53504719 0.46495281]
 [0.57904672 0.42095328]
 [0.5319147  0.4680853 ]
 [0.5        0.5       ]
 [0.51484706 0.48515294]
 [0.52813652 0.47186348]
 [0.45248021 0.54751979]
 [0.5300678  0.4699322 ]
 [0.4239224  0.5760776 ]
 [0.52310397 0.47689603]
 [0.52659478 0.47340522]
 [0.53577772 0.46422228]
 [0.58083802 0.41916198]
 [0.53896793 0.46103207]
 [0.56410167 0.43589833]
 [0.5        0.5       ]
 [0.44862084 0.55137916]
 [0.5        0.5       ]
 [0.46708946 0.53291054]
 [0.56156852 0.43843148]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.4452106  0.5547894 ]
 [0.47341188 0.52658812]
 [0.5610945  0.4389055 ]
 ...
 [0.5        0.5       ]
 [0.48509726 0.51490274]
 [0.54000334 0.45999666]]
{'Positive': 0, 'Negative': 0}
Positive
[[0.48279013 0.51720987]
 [0.54259956 0.45740044]
 [0.51403697 0.48596303]
 [0.52080423 0.47919577]
 [0.47640736 0.52359264]
 [0.51266527 0.48733473]
 [0.51877383 0.48122617]]
{'Positive': 0, 'Negative': 0}
Positive
[[0.42877686 0.57122314]
 [0.41750827 0.58249173]
 [0.44334127 0.55665873]
 [0.55774759 0.44225241]
 [0.54639016 0.45360984]
 [0.58565114 0.41434886]
 [0.54057874 0.45942126]
 [0.52335962 0.47664038]
 [0.5        0.5       ]
 [0.51156526 0.48843474]
 [0.46919703 0.53080297]
 [0.48087169 0.51912831]
 [0.51539517 0.48460483]
 [0.50522022 0.49477978]
 [0.56451138 0.43548862]
 [0.47410156 0.52589844]
 [0.58187905 0.41812095]
 [0.53850014 0.46149986]
 [0.4669411  0.5330589 ]
 [0.46116759 0.53883241]
 [0.52269552 0.47730448]
 [0.44002776 0.55997224]
 [0.52628395 0.47371605]
 [0.44201372 

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.49479777 0.50520223]
 [0.46952403 0.53047597]
 [0.49490025 0.50509975]
 [0.42591798 0.57408202]
 [0.47338557 0.52661443]
 [0.51053069 0.48946931]
 [0.51203187 0.48796813]
 [0.53568107 0.46431893]
 [0.54242827 0.45757173]
 [0.47140644 0.52859356]
 [0.49097771 0.50902229]
 [0.41889461 0.58110539]
 [0.42493784 0.57506216]
 [0.5332844  0.4667156 ]
 [0.42921696 0.57078304]
 [0.52544805 0.47455195]
 [0.45132523 0.54867477]
 [0.5078015  0.4921985 ]
 [0.48598131 0.51401869]
 [0.42845576 0.57154424]
 [0.44182246 0.55817754]
 [0.46757675 0.53242325]
 [0.56712453 0.43287547]
 [0.5124892  0.4875108 ]
 [0.52670789 0.47329211]
 [0.5        0.5       ]
 [0.48071159 0.51928841]
 [0.53412667 0.46587333]
 [0.46386132 0.53613868]
 [0.44625249 0.55374751]
 [0.46229898 0.53770102]
 [0.53714896 0.46285104]
 [0.51078249 0.48921751]
 [0.45512652 0.54487348]
 [0.52152613 0.47847387]
 [0.46728594 0.53271406]
 [0.54019585 0.45980415]
 [0.46428557 0.53571443]
 [0.54360942 0.45639058]
 [0.53659933 0.46340067]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.47986261 0.52013739]
 [0.44284076 0.55715924]
 [0.44948678 0.55051322]
 [0.48174158 0.51825842]
 [0.49042942 0.50957058]
 [0.48789088 0.51210912]
 [0.43098811 0.56901189]
 [0.5        0.5       ]
 [0.49270846 0.50729154]
 [0.5        0.5       ]
 [0.47037803 0.52962197]
 [0.41847968 0.58152032]
 [0.46998771 0.53001229]
 [0.43650518 0.56349482]
 [0.47809145 0.52190855]
 [0.48375641 0.51624359]
 [0.5        0.5       ]
 [0.39398839 0.60601161]
 [0.38460613 0.61539387]
 [0.44731619 0.55268381]
 [0.40424773 0.59575227]
 [0.4518827  0.5481173 ]
 [0.52277174 0.47722826]
 [0.45328777 0.54671223]
 [0.45377613 0.54622387]
 [0.45413491 0.54586509]
 [0.5380803  0.4619197 ]
 [0.54490461 0.45509539]
 [0.55605439 0.44394561]
 [0.51818149 0.48181851]
 [0.51458169 0.48541831]
 [0.52997504 0.47002496]
 [0.44302474 0.55697526]
 [0.5        0.5       ]
 [0.51214412 0.48785588]
 [0.49427839 0.50572161]
 [0.50840206 0.49159794]
 [0.47515511 0.52484489]
 [0.5        0.5       ]
 [0.49078243 0.50921757]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.59073864 0.40926136]
 [0.56471387 0.43528613]
 [0.54362352 0.45637648]
 [0.55809359 0.44190641]
 [0.56635473 0.43364527]
 [0.56641287 0.43358713]
 [0.54159957 0.45840043]
 [0.53218736 0.46781264]
 [0.5232766  0.4767234 ]
 [0.57756873 0.42243127]
 [0.5        0.5       ]
 [0.56649986 0.43350014]
 [0.59341086 0.40658914]
 [0.55490036 0.44509964]
 [0.58213532 0.41786468]
 [0.53990702 0.46009298]
 [0.5        0.5       ]
 [0.44279457 0.55720543]
 [0.5773809  0.4226191 ]
 [0.48270024 0.51729976]
 [0.52697971 0.47302029]
 [0.5314393  0.4685607 ]
 [0.55733432 0.44266568]
 [0.5        0.5       ]
 [0.54876131 0.45123869]
 [0.54557945 0.45442055]
 [0.45011136 0.54988864]
 [0.50504221 0.49495779]
 [0.55565414 0.44434586]
 [0.51960992 0.48039008]
 [0.53296608 0.46703392]
 [0.42359739 0.57640261]
 [0.54194079 0.45805921]
 [0.53970419 0.46029581]
 [0.55217009 0.44782991]
 [0.50999367 0.49000633]
 [0.55471893 0.44528107]
 [0.52300085 0.47699915]
 [0.55553068 0.44446932]
 [0.52887407 0.47112593]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.5        0.5       ]
 [0.46814864 0.53185136]
 [0.48260759 0.51739241]
 [0.48388854 0.51611146]
 [0.44666548 0.55333452]
 [0.45984267 0.54015733]
 [0.49300623 0.50699377]
 [0.46459919 0.53540081]
 [0.48591301 0.51408699]
 [0.47908    0.52092   ]
 [0.4935227  0.5064773 ]
 [0.4861651  0.5138349 ]
 [0.4772062  0.5227938 ]
 [0.51340359 0.48659641]
 [0.48389161 0.51610839]
 [0.47822442 0.52177558]
 [0.47137954 0.52862046]
 [0.47445436 0.52554564]
 [0.45280477 0.54719523]
 [0.50975813 0.49024187]
 [0.46980401 0.53019599]
 [0.43556865 0.56443135]
 [0.45691469 0.54308531]
 [0.46178567 0.53821433]
 [0.48786298 0.51213702]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.42577529 0.57422471]
 [0.47136202 0.52863798]
 [0.47916291 0.52083709]
 [0.45630366 0.54369634]
 [0.4792158  0.5207842 ]
 [0.48652037 0.51347963]
 [0.46198981 0.53801019]
 [0.4562946  0.5437054 ]
 [0.43215513 0.56784487]
 [0.43169169 0.56830831]
 [0.51116124 0.48883876]
 [0.46818989 0.53181011]
 [0.46667337 0.53332663]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.55436902 0.44563098]
 [0.5        0.5       ]
 [0.48821856 0.51178144]
 ...
 [0.46255017 0.53744983]
 [0.53674642 0.46325358]
 [0.51706588 0.48293412]]
{'Positive': 0, 'Negative': 0}
Negative
[[0.53951792 0.46048208]
 [0.54490428 0.45509572]
 [0.51421488 0.48578512]
 [0.44325995 0.55674005]
 [0.57608118 0.42391882]
 [0.53716304 0.46283696]
 [0.45715615 0.54284385]
 [0.57360832 0.42639168]
 [0.53029869 0.46970131]
 [0.5560641  0.4439359 ]
 [0.46418614 0.53581386]
 [0.54313418 0.45686582]
 [0.5        0.5       ]
 [0.53657687 0.46342313]
 [0.53484293 0.46515707]
 [0.56316135 0.43683865]
 [0.43139185 0.56860815]
 [0.56442856 0.43557144]
 [0.55734674 0.44265326]
 [0.55937763 0.44062237]
 [0.571699   0.428301  ]
 [0.55037747 0.44962253]
 [0.57397099 0.42602901]
 [0.56926382 0.43073618]
 [0.56676175 0.43323825]
 [0.46884484 0.53115516]
 [0.53088092 0.46911908]
 [0.5        0.5       ]
 [0.44618087 0.55381913]
 [0.51450858 0.48549142]
 [0.55253213 0.44746787]
 [0.36281217 0.63718783]
 [0.

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.44421168 0.55578832]
 [0.48841937 0.51158063]
 [0.53890962 0.46109038]
 [0.45015855 0.54984145]
 [0.52165866 0.47834134]
 [0.56614692 0.43385308]
 [0.5322364  0.4677636 ]
 [0.56121517 0.43878483]
 [0.52161112 0.47838888]
 [0.54502446 0.45497554]
 [0.51127988 0.48872012]
 [0.48686021 0.51313979]
 [0.47563786 0.52436214]
 [0.5258058  0.4741942 ]
 [0.54033667 0.45966333]
 [0.54868762 0.45131238]
 [0.47092856 0.52907144]
 [0.51654486 0.48345514]
 [0.5        0.5       ]
 [0.53502142 0.46497858]
 [0.5537871  0.4462129 ]
 [0.48993942 0.51006058]
 [0.51764033 0.48235967]
 [0.48544655 0.51455345]
 [0.5        0.5       ]
 [0.56737374 0.43262626]
 [0.49410162 0.50589838]
 [0.5        0.5       ]
 [0.54006002 0.45993998]
 [0.51767161 0.48232839]
 [0.55842659 0.44157341]
 [0.56310737 0.43689263]
 [0.55813751 0.44186249]
 [0.58415195 0.41584805]
 [0.52135287 0.47864713]
 [0.5269796  0.4730204 ]
 [0.53984514 0.46015486]
 [0.49316972 0.50683028]
 [0.52370936 0.47629064]
 [0.50777034 0.49222966]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.51932504 0.48067496]
 [0.52002941 0.47997059]
 [0.51007299 0.48992701]
 ...
 [0.46828775 0.53171225]
 [0.5        0.5       ]
 [0.5        0.5       ]]
{'Positive': 0, 'Negative': 0}
Negative


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.49424463 0.50575537]
 [0.45815572 0.54184428]
 [0.46962093 0.53037907]
 ...
 [0.50680361 0.49319639]
 [0.44970891 0.55029109]
 [0.50501261 0.49498739]]
{'Positive': 0, 'Negative': 0}
Negative
[[0.44721369 0.55278631]
 [0.45818007 0.54181993]
 [0.44945628 0.55054372]
 [0.49086291 0.50913709]
 [0.4528018  0.5471982 ]
 [0.48541072 0.51458928]
 [0.43258305 0.56741695]
 [0.47006535 0.52993465]
 [0.47631093 0.52368907]
 [0.46702548 0.53297452]
 [0.51347389 0.48652611]
 [0.4670907  0.5329093 ]
 [0.49436607 0.50563393]
 [0.46215782 0.53784218]
 [0.48757884 0.51242116]
 [0.48750333 0.51249667]
 [0.48193906 0.51806094]
 [0.51542901 0.48457099]
 [0.47772262 0.52227738]
 [0.45234708 0.54765292]
 [0.43393858 0.56606142]
 [0.41626886 0.58373114]
 [0.44918804 0.55081196]
 [0.5        0.5       ]
 [0.4697885  0.5302115 ]
 [0.48218988 0.51781012]
 [0.4135995  0.5864005 ]
 [0.4772031  0.5227969 ]
 [0.47774671 0.52225329]
 [0.47478846 0.52521154]
 [0.4342702  0.5657298 ]
 [0.45747118 0.54252882]
 [0.

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.39340647 0.60659353]
 [0.47626196 0.52373804]
 [0.5        0.5       ]
 [0.56866481 0.43133519]
 [0.58498044 0.41501956]
 [0.46159421 0.53840579]
 [0.56321743 0.43678257]
 [0.5        0.5       ]
 [0.56403764 0.43596236]
 [0.42176767 0.57823233]
 [0.51831271 0.48168729]
 [0.47549845 0.52450155]
 [0.54665007 0.45334993]
 [0.54725333 0.45274667]
 [0.4746651  0.5253349 ]
 [0.57066066 0.42933934]
 [0.54760481 0.45239519]
 [0.50512415 0.49487585]
 [0.5786201  0.4213799 ]
 [0.5        0.5       ]
 [0.48922039 0.51077961]
 [0.53148018 0.46851982]
 [0.55748537 0.44251463]
 [0.45027132 0.54972868]
 [0.57251439 0.42748561]
 [0.5        0.5       ]
 [0.51563149 0.48436851]
 [0.49064064 0.50935936]
 [0.54743656 0.45256344]
 [0.44263745 0.55736255]
 [0.49118378 0.50881622]
 [0.56162479 0.43837521]
 [0.56061131 0.43938869]
 [0.47849935 0.52150065]
 [0.51014143 0.48985857]
 [0.5241644  0.4758356 ]
 [0.46118155 0.53881845]
 [0.43888412 0.56111588]
 [0.54641184 0.45358816]
 [0.45076337 0.54923663]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.42763213 0.57236787]
 [0.55512952 0.44487048]
 [0.55843551 0.44156449]
 [0.40894663 0.59105337]
 [0.55355102 0.44644898]
 [0.52042151 0.47957849]
 [0.47324961 0.52675039]
 [0.56616149 0.43383851]
 [0.54710557 0.45289443]
 [0.52213793 0.47786207]
 [0.53583215 0.46416785]
 [0.46271878 0.53728122]
 [0.44900722 0.55099278]
 [0.54255817 0.45744183]
 [0.47874056 0.52125944]
 [0.5400304  0.4599696 ]
 [0.58082935 0.41917065]
 [0.57626547 0.42373453]
 [0.5255362  0.4744638 ]
 [0.57351171 0.42648829]
 [0.56727974 0.43272026]
 [0.57214127 0.42785873]
 [0.55499446 0.44500554]
 [0.51286853 0.48713147]
 [0.58013578 0.41986422]
 [0.55727954 0.44272046]
 [0.51520865 0.48479135]
 [0.5810843  0.4189157 ]
 [0.56885043 0.43114957]
 [0.54072256 0.45927744]
 [0.53346555 0.46653445]
 [0.56381233 0.43618767]
 [0.53494242 0.46505758]
 [0.55607549 0.44392451]
 [0.55873756 0.44126244]
 [0.54620607 0.45379393]
 [0.5652695  0.4347305 ]
 [0.58997727 0.41002273]
 [0.52879259 0.47120741]
 [0.50513341 0.49486659]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.52549521 0.47450479]
 [0.43539329 0.56460671]
 [0.52964745 0.47035255]
 [0.5        0.5       ]
 [0.49339892 0.50660108]
 [0.53134747 0.46865253]
 [0.5        0.5       ]
 [0.52688374 0.47311626]
 [0.57035088 0.42964912]
 [0.50660282 0.49339718]
 [0.51603563 0.48396437]
 [0.5        0.5       ]
 [0.55680153 0.44319847]
 [0.4730613  0.5269387 ]
 [0.49329756 0.50670244]
 [0.50755567 0.49244433]
 [0.54663112 0.45336888]
 [0.5        0.5       ]
 [0.55622269 0.44377731]
 [0.5        0.5       ]
 [0.51580518 0.48419482]
 [0.54084875 0.45915125]
 [0.48815446 0.51184554]
 [0.53038697 0.46961303]
 [0.53457867 0.46542133]
 [0.4621166  0.5378834 ]
 [0.52343134 0.47656866]
 [0.54587035 0.45412965]
 [0.45915284 0.54084716]
 [0.5        0.5       ]
 [0.51338445 0.48661555]
 [0.53384125 0.46615875]
 [0.52932829 0.47067171]
 [0.52600321 0.47399679]
 [0.45717869 0.54282131]
 [0.44874168 0.55125832]
 [0.54817751 0.45182249]
 [0.44322583 0.55677417]
 [0.45116265 0.54883735]
 [0.51461822 0.48538178]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.54985135 0.45014865]
 [0.47619165 0.52380835]
 [0.5155144  0.4844856 ]
 [0.57391073 0.42608927]
 [0.467845   0.532155  ]
 [0.53179515 0.46820485]
 [0.50926741 0.49073259]
 [0.48542173 0.51457827]
 [0.5        0.5       ]
 [0.55877987 0.44122013]
 [0.45266895 0.54733105]
 [0.48044832 0.51955168]
 [0.42631297 0.57368703]
 [0.49249598 0.50750402]
 [0.47778909 0.52221091]
 [0.56261634 0.43738366]
 [0.52852407 0.47147593]
 [0.47848961 0.52151039]
 [0.42979765 0.57020235]
 [0.57226819 0.42773181]
 [0.54038723 0.45961277]
 [0.53498192 0.46501808]
 [0.50955866 0.49044134]
 [0.53033115 0.46966885]
 [0.52601707 0.47398293]
 [0.54127132 0.45872868]
 [0.41823238 0.58176762]
 [0.47736731 0.52263269]
 [0.42356066 0.57643934]
 [0.48767321 0.51232679]
 [0.46273164 0.53726836]
 [0.4780689  0.5219311 ]
 [0.441221   0.558779  ]
 [0.41545959 0.58454041]
 [0.5127571  0.4872429 ]
 [0.55549352 0.44450648]
 [0.5117398  0.4882602 ]
 [0.53802576 0.46197424]
 [0.46014808 0.53985192]
 [0.55375377 0.44624623]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.44091866 0.55908134]
 [0.44727174 0.55272826]
 [0.5193776  0.4806224 ]
 [0.51378253 0.48621747]
 [0.46515043 0.53484957]
 [0.51733335 0.48266665]
 [0.48365526 0.51634474]
 [0.51888829 0.48111171]
 [0.5237206  0.4762794 ]
 [0.4597973  0.5402027 ]
 [0.5        0.5       ]
 [0.46351708 0.53648292]
 [0.5        0.5       ]
 [0.41098986 0.58901014]
 [0.4944193  0.5055807 ]
 [0.5236499  0.4763501 ]
 [0.41563381 0.58436619]
 [0.44739736 0.55260264]
 [0.48253746 0.51746254]
 [0.5        0.5       ]
 [0.46653856 0.53346144]
 [0.5        0.5       ]
 [0.43996844 0.56003156]
 [0.49481509 0.50518491]
 [0.43965185 0.56034815]
 [0.50740842 0.49259158]
 [0.52100273 0.47899727]
 [0.5        0.5       ]
 [0.43650086 0.56349914]
 [0.53333206 0.46666794]
 [0.4633013  0.5366987 ]
 [0.52563991 0.47436009]
 [0.4471648  0.5528352 ]
 [0.43019253 0.56980747]
 [0.50909516 0.49090484]
 [0.50888432 0.49111568]
 [0.5        0.5       ]
 [0.46676545 0.53323455]
 [0.46978784 0.53021216]
 [0.5        0.5       ]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.54156207 0.45843793]
 [0.5        0.5       ]
 [0.54624996 0.45375004]
 [0.53373841 0.46626159]
 [0.5197227  0.4802773 ]
 [0.41646958 0.58353042]
 [0.5        0.5       ]
 [0.51013288 0.48986712]
 [0.56172341 0.43827659]
 [0.51331581 0.48668419]
 [0.41279036 0.58720964]
 [0.44673792 0.55326208]
 [0.45589477 0.54410523]
 [0.41280372 0.58719628]
 [0.46323258 0.53676742]
 [0.49049571 0.50950429]
 [0.5        0.5       ]
 [0.51999445 0.48000555]
 [0.5        0.5       ]
 [0.44878459 0.55121541]
 [0.51698844 0.48301156]
 [0.53772391 0.46227609]
 [0.5        0.5       ]
 [0.45882492 0.54117508]
 [0.5650143  0.4349857 ]
 [0.50760606 0.49239394]
 [0.43128469 0.56871531]
 [0.46094347 0.53905653]
 [0.58051645 0.41948355]
 [0.46776511 0.53223489]
 [0.50964833 0.49035167]
 [0.53640361 0.46359639]
 [0.53130285 0.46869715]
 [0.48874508 0.51125492]
 [0.51685022 0.48314978]
 [0.52713925 0.47286075]
 [0.5        0.5       ]
 [0.55188373 0.44811627]
 [0.44996679 0.55003321]
 [0.54946201 0.45053799]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.53289574 0.46710426]
 [0.52647084 0.47352916]
 [0.51814283 0.48185717]
 [0.55112691 0.44887309]
 [0.52628435 0.47371565]
 [0.52911072 0.47088928]
 [0.51327396 0.48672604]
 [0.50631566 0.49368434]
 [0.5608748  0.4391252 ]
 [0.5        0.5       ]
 [0.42778596 0.57221404]
 [0.49240473 0.50759527]
 [0.52393485 0.47606515]
 [0.46774029 0.53225971]
 [0.5075925  0.4924075 ]
 [0.50644205 0.49355795]
 [0.54040989 0.45959011]
 [0.5124752  0.4875248 ]
 [0.52527074 0.47472926]
 [0.51311959 0.48688041]
 [0.5        0.5       ]
 [0.56929004 0.43070996]
 [0.51535385 0.48464615]
 [0.51376198 0.48623802]
 [0.53166203 0.46833797]
 [0.48474385 0.51525615]
 [0.5        0.5       ]
 [0.5306322  0.4693678 ]
 [0.51334953 0.48665047]
 [0.48825924 0.51174076]
 [0.47617578 0.52382422]
 [0.5        0.5       ]
 [0.56655659 0.43344341]
 [0.52061524 0.47938476]
 [0.53432744 0.46567256]
 [0.49013049 0.50986951]
 [0.5146065  0.4853935 ]
 [0.50831795 0.49168205]
 [0.530942   0.469058  ]
 [0.52176956 0.47823044]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.4858291  0.5141709 ]
 [0.53249691 0.46750309]
 [0.47595404 0.52404596]
 [0.5        0.5       ]
 [0.520704   0.479296  ]
 [0.46920786 0.53079214]
 [0.48761385 0.51238615]
 [0.50557369 0.49442631]
 [0.53309352 0.46690648]
 [0.490078   0.509922  ]
 [0.55195857 0.44804143]
 [0.51127177 0.48872823]
 [0.5676307  0.4323693 ]
 [0.40380734 0.59619266]
 [0.57191936 0.42808064]
 [0.54485839 0.45514161]
 [0.43572358 0.56427642]
 [0.45622138 0.54377862]
 [0.5        0.5       ]
 [0.52127484 0.47872516]
 [0.52425575 0.47574425]
 [0.56203833 0.43796167]
 [0.40712578 0.59287422]
 [0.44289448 0.55710552]
 [0.51384949 0.48615051]
 [0.53370666 0.46629334]
 [0.56626273 0.43373727]
 [0.55587261 0.44412739]
 [0.43778313 0.56221687]
 [0.5        0.5       ]
 [0.43804136 0.56195864]
 [0.517649   0.482351  ]
 [0.5335655  0.4664345 ]
 [0.59918985 0.40081015]
 [0.5        0.5       ]
 [0.39995398 0.60004602]
 [0.49094605 0.50905395]
 [0.56346813 0.43653187]
 [0.49083001 0.50916999]
 [0.47644473 0.52355527]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.47890277 0.52109723]
 [0.54550038 0.45449962]
 [0.51356353 0.48643647]
 ...
 [0.44789208 0.55210792]
 [0.55576134 0.44423866]
 [0.46167986 0.53832014]]
{'Positive': 0, 'Negative': 0}
Negative
[[0.5        0.5       ]
 [0.53114439 0.46885561]
 [0.47484375 0.52515625]
 [0.44083404 0.55916596]
 [0.49225231 0.50774769]
 [0.45205523 0.54794477]
 [0.54788736 0.45211264]
 [0.53752894 0.46247106]
 [0.53138396 0.46861604]
 [0.49457315 0.50542685]
 [0.49005301 0.50994699]
 [0.43799975 0.56200025]
 [0.55766639 0.44233361]
 [0.5        0.5       ]
 [0.47078551 0.52921449]
 [0.46423491 0.53576509]
 [0.5        0.5       ]
 [0.52358373 0.47641627]
 [0.42640324 0.57359676]
 [0.45114261 0.54885739]
 [0.42665848 0.57334152]
 [0.48078615 0.51921385]
 [0.43636214 0.56363786]
 [0.55589273 0.44410727]
 [0.51708912 0.48291088]
 [0.52423522 0.47576478]
 [0.44175426 0.55824574]
 [0.47917407 0.52082593]
 [0.45200987 0.54799013]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.4802031  0.5197969 ]
 [0.

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.46667592 0.53332408]
 [0.42307871 0.57692129]
 [0.46938674 0.53061326]
 [0.45844588 0.54155412]
 [0.56156172 0.43843828]
 [0.52740634 0.47259366]
 [0.50929838 0.49070162]
 [0.47592178 0.52407822]
 [0.48397722 0.51602278]
 [0.52920581 0.47079419]
 [0.5621696  0.4378304 ]
 [0.5196026  0.4803974 ]
 [0.46019965 0.53980035]
 [0.42391276 0.57608724]
 [0.52868169 0.47131831]
 [0.42378019 0.57621981]
 [0.5        0.5       ]
 [0.42979381 0.57020619]
 [0.49340006 0.50659994]
 [0.54445967 0.45554033]
 [0.53789875 0.46210125]
 [0.48586521 0.51413479]
 [0.46966697 0.53033303]
 [0.5        0.5       ]
 [0.52130441 0.47869559]
 [0.46835219 0.53164781]
 [0.5        0.5       ]
 [0.43310866 0.56689134]
 [0.47747241 0.52252759]
 [0.43930041 0.56069959]
 [0.5214093  0.4785907 ]
 [0.45418544 0.54581456]
 [0.55377272 0.44622728]
 [0.47690397 0.52309603]
 [0.48430715 0.51569285]
 [0.45825361 0.54174639]
 [0.42922994 0.57077006]
 [0.51819617 0.48180383]
 [0.48135638 0.51864362]
 [0.45098519 0.54901481]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.44038911 0.55961089]
 [0.51568016 0.48431984]
 [0.4635121  0.5364879 ]
 [0.4790929  0.5209071 ]
 [0.49194192 0.50805808]
 [0.43170621 0.56829379]
 [0.52809378 0.47190622]
 [0.48764449 0.51235551]
 [0.5        0.5       ]
 [0.46001968 0.53998032]
 [0.45924278 0.54075722]
 [0.51649379 0.48350621]
 [0.49431618 0.50568382]
 [0.44998614 0.55001386]
 [0.5223974  0.4776026 ]
 [0.52976421 0.47023579]
 [0.4941481  0.5058519 ]
 [0.50693042 0.49306958]
 [0.48978244 0.51021756]
 [0.48479798 0.51520202]
 [0.46774728 0.53225272]
 [0.5254141  0.4745859 ]
 [0.48905984 0.51094016]
 [0.47597841 0.52402159]
 [0.52802598 0.47197402]
 [0.46814581 0.53185419]
 [0.45298512 0.54701488]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.53438536 0.46561464]
 [0.52704745 0.47295255]
 [0.47526224 0.52473776]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.51305719 0.48694281]
 [0.41894181 0.58105819]
 [0.53711693 0.46288307]
 [0.53980531 0.46019469]
 [0.44651429 0.55348571]
 [0.4856296  0.5143704 ]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWar

[[0.48110966 0.51889034]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.42152512 0.57847488]
 [0.55483879 0.44516121]
 [0.53041983 0.46958017]
 [0.46448231 0.53551769]
 [0.51245659 0.48754341]
 [0.55282786 0.44717214]
 [0.46029043 0.53970957]
 [0.5        0.5       ]
 [0.56595042 0.43404958]
 [0.53296665 0.46703335]
 [0.53795417 0.46204583]
 [0.51828256 0.48171744]
 [0.44577962 0.55422038]
 [0.49025093 0.50974907]
 [0.47542225 0.52457775]
 [0.53616598 0.46383402]
 [0.49353331 0.50646669]
 [0.5405943  0.4594057 ]
 [0.55915525 0.44084475]
 [0.50847988 0.49152012]
 [0.53710272 0.46289728]
 [0.47987093 0.52012907]
 [0.45958461 0.54041539]
 [0.52227353 0.47772647]
 [0.46521703 0.53478297]
 [0.44433832 0.55566168]
 [0.46196712 0.53803288]
 [0.55283817 0.44716183]
 [0.45075956 0.54924044]
 [0.5579405  0.4420595 ]
 [0.5        0.5       ]
 [0.40382869 0.59617131]
 [0.5        0.5       ]
 [0.51825764 0.48174236]
 [0.50591574 0.49408426]
 [0.52321586 0.47678414]
 [0.45200218 0.54799782]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.55985298 0.44014702]
 [0.53364729 0.46635271]
 [0.54791711 0.45208289]
 [0.51917308 0.48082692]
 [0.58542673 0.41457327]
 [0.51923042 0.48076958]
 [0.5540184  0.4459816 ]
 [0.47508515 0.52491485]
 [0.52860694 0.47139306]
 [0.52622224 0.47377776]
 [0.52434694 0.47565306]
 [0.56838516 0.43161484]
 [0.5140184  0.4859816 ]
 [0.5198004  0.4801996 ]
 [0.46585844 0.53414156]
 [0.5        0.5       ]
 [0.42505739 0.57494261]
 [0.55229591 0.44770409]
 [0.57531994 0.42468006]
 [0.54324117 0.45675883]
 [0.5391954  0.4608046 ]
 [0.51640425 0.48359575]
 [0.59134959 0.40865041]
 [0.54343004 0.45656996]
 [0.533452   0.466548  ]
 [0.60524947 0.39475053]
 [0.40671744 0.59328256]
 [0.44137206 0.55862794]
 [0.46303574 0.53696426]
 [0.52932717 0.47067283]
 [0.51126414 0.48873586]
 [0.48273474 0.51726526]
 [0.54539599 0.45460401]
 [0.57973721 0.42026279]
 [0.5        0.5       ]
 [0.46348857 0.53651143]
 [0.49386602 0.50613398]
 [0.57171469 0.42828531]
 [0.57214079 0.42785921]
 [0.42242043 0.57757957]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.52629809 0.47370191]
 [0.47594692 0.52405308]
 [0.47333143 0.52666857]
 ...
 [0.46408134 0.53591866]
 [0.48415501 0.51584499]
 [0.4274314  0.5725686 ]]
{'Positive': 0, 'Negative': 0}
Negative


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.5        0.5       ]
 [0.50855447 0.49144553]
 [0.47951011 0.52048989]
 [0.53392708 0.46607292]
 [0.43855276 0.56144724]
 [0.52393592 0.47606408]
 [0.47661928 0.52338072]
 [0.43980004 0.56019996]
 [0.51387698 0.48612302]
 [0.48834003 0.51165997]
 [0.43312098 0.56687902]
 [0.5        0.5       ]
 [0.4004392  0.5995608 ]
 [0.5        0.5       ]
 [0.5078267  0.4921733 ]
 [0.55323051 0.44676949]
 [0.45974227 0.54025773]
 [0.49259671 0.50740329]
 [0.47900317 0.52099683]
 [0.48240429 0.51759571]
 [0.45496935 0.54503065]
 [0.5        0.5       ]
 [0.44552318 0.55447682]
 [0.5        0.5       ]
 [0.46229615 0.53770385]
 [0.51748455 0.48251545]
 [0.50910658 0.49089342]
 [0.49137375 0.50862625]
 [0.48121725 0.51878275]
 [0.49087331 0.50912669]
 [0.45868465 0.54131535]
 [0.46969992 0.53030008]
 [0.49193705 0.50806295]
 [0.46743421 0.53256579]
 [0.48779221 0.51220779]
 [0.47128089 0.52871911]
 [0.48728147 0.51271853]
 [0.40707846 0.59292154]
 [0.46069392 0.53930608]
 [0.48527941 0.51472059]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.4395616  0.5604384 ]
 [0.46507924 0.53492076]
 [0.43825056 0.56174944]
 [0.44282947 0.55717053]
 [0.53199128 0.46800872]
 [0.47098365 0.52901635]
 [0.4627647  0.5372353 ]
 [0.50649898 0.49350102]
 [0.47777255 0.52222745]
 [0.48042344 0.51957656]
 [0.43832193 0.56167807]
 [0.43438345 0.56561655]
 [0.43731839 0.56268161]
 [0.47883003 0.52116997]
 [0.46745238 0.53254762]
 [0.5147043  0.4852957 ]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.45382613 0.54617387]
 [0.5        0.5       ]
 [0.5        0.5       ]
 [0.47664151 0.52335849]
 [0.44116765 0.55883235]
 [0.48497501 0.51502499]
 [0.4787444  0.5212556 ]
 [0.46714261 0.53285739]
 [0.4762645  0.5237355 ]
 [0.52713666 0.47286334]
 [0.43510022 0.56489978]
 [0.49386356 0.50613644]
 [0.50683275 0.49316725]
 [0.55658699 0.44341301]
 [0.47576889 0.52423111]
 [0.48409563 0.51590437]
 [0.53596263 0.46403737]
 [0.46561043 0.53438957]
 [0.47168315 0.52831685]
 [0.4586419  0.5413581 ]
 [0.4447565  0.5552435 ]
 [0.42591209 0.57408791]


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.47793896 0.52206104]
 [0.47810219 0.52189781]
 [0.43001408 0.56998592]
 ...
 [0.46736689 0.53263311]
 [0.42810097 0.57189903]
 [0.45633743 0.54366257]]
{'Positive': 0, 'Negative': 0}
Negative
[[0.5        0.5       ]
 [0.54919771 0.45080229]
 [0.56027972 0.43972028]
 [0.56000751 0.43999249]
 [0.5399723  0.4600277 ]
 [0.54546266 0.45453734]
 [0.5731454  0.4268546 ]
 [0.55931788 0.44068212]
 [0.54663442 0.45336558]
 [0.53412278 0.46587722]
 [0.53859779 0.46140221]
 [0.5        0.5       ]
 [0.5450736  0.4549264 ]
 [0.55614562 0.44385438]
 [0.5        0.5       ]
 [0.53687753 0.46312247]
 [0.54389542 0.45610458]
 [0.56066206 0.43933794]
 [0.54258462 0.45741538]
 [0.51068765 0.48931235]
 [0.59569971 0.40430029]
 [0.52661287 0.47338713]
 [0.51198958 0.48801042]
 [0.55822438 0.44177562]
 [0.45537933 0.54462067]
 [0.56260312 0.43739688]
 [0.53070243 0.46929757]
 [0.56370563 0.43629437]
 [0.5193565  0.4806435 ]
 [0.55819882 0.44180118]
 [0.44790888 0.55209112]
 [0.54560198 0.45439802]
 [0.

/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])
/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


[[0.46980883 0.53019117]
 [0.54093891 0.45906109]
 [0.48846984 0.51153016]
 ...
 [0.46245515 0.53754485]
 [0.42585478 0.57414522]
 [0.39559474 0.60440526]]
{'Positive': 0, 'Negative': 0}


/tmp/ipykernel_8449/1463982065.py:135: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Positive"] = len([p for p in predictions if p == "Positive"])
/tmp/ipykernel_8449/1463982065.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  results["Negative"] = len([p for p in predictions if p == "Negative"])


In [45]:
np.array(saliva_confusion_matrix_svc)

array([[42,  0],
       [47,  0]])